# We do not use sudo
sudo: false

# Python versions for matrix
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# Django versions for matrix
env:
  - DJANGO_VERSION='>=1.10,<1.11'
  - DJANGO_VERSION='>=1.11,<1.12'
  - DJANGO_VERSION='>=2.0,<2.2'

# Command to install dependencies, e.g. pip install -r requirements.txt
install:
  - pip install Django$DJANGO_VERSION
  - pip install coveralls
  - pip install python-coveralls

# Command to run tests, e.g. python setup.py test
script:
  - pip install -r requirements.txt
  - coverage run --source=django_propeller manage.py test
  - python manage.py check

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION='>=1.9,<1.10'
    - python: "3.3"
      env: DJANGO_VERSION='>=1.10,<1.11'

# Report to coveralls
after_success:
  - COVERALLS_REPO_TOKEN=zhYHkOdDrdEtPvuCowlDRTzI4kEYmwn1B coveralls
